name = "calyx-site"
compatibility_date = "2026-05-07"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Optional: Add Node.js compatibility if you use node: namespaces
compatibility_flags = ["nodejs_compat"]
